name: pluginslab
version: '1.0.6'
author: Kstars
main: fr.kstars.pluginslab.Main
api-version: '1.21'
commands:
  spawn:
    description: Teleports you to the spawn point
  teleport:
    description: Teleports yourself or another player to a target player
    aliases: tp
  heal:
    description: Heals yourself or a target player
  feed:
    description: Restores the hunger of yourself or a target player
  kill:
    description: Kills yourself or a target player
  gamemode:
    description: Changes your own or another player's game mode
    aliases: gm
  fly:
    description: Activates or deactivates the fly to you or a target player
  kick:
    description: Exclude a person from the server
